self-hosted-runner:
    labels:
        - Linux
        - X64
        - racknerd
        - aws-india
        - light
        - cpu40
        - codeql
        - codeql-general
        - blacksmith-2vcpu-ubuntu-2404
